name: Web application
on:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/workflows/webapp.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/workflows/webapp.yml'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install global dependencies
        uses: bahmutov/npm-install@v1

      - name: Install web application dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: webapp

      - run: yarn type:check
      - run: yarn lint

      - name: Run unit tests
        working-directory: webapp
        run: yarn test
